package: nv_modulepresets # Pflichtfeld
version: '1.0.0-beta' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://github.com/novinet-git/nv_modulepresets


page:
    title: translate:nv_modulepresets_key
    icon: novinet-icon-logo
    perm: 'nv_modulepresets'
    pjax: false
    subpages:
            presets: { title: translate:nv_modulepresets }

requires:
    php:
        version: '>=7.2'
    redaxo: '^5.7'
    packages:
        nv_modulepreview: '>=1.5-beta'